"use client";
import { useParams } from "next/navigation";
import jsPDF from "jspdf";
import { getCompany } from "@/app/lib/companyStore";
import { useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabase";


export default function InvoicePage(){

const params = useParams();
const [company, setCompany] = useState<any>(null);
useEffect(()=>{

const data = getCompany();

console.log("COMPANY DATA:", data);

setCompany(data);

},[]);
console.log("LOGO CHECK:", company?.logo);

console.log(company);
const downloadPDF = () => {

const doc = new jsPDF();

// Logo
if (company?.logo) {
  doc.addImage(company.logo, "PNG", 20, 15, 30, 30);
}

// Company
doc.setFont("helvetica", "bold");
doc.setFontSize(24);
doc.text(company?.name || "Freelancer SaaS", 20, 22);

// Invoice Title
doc.setFontSize(28);
doc.text("INVOICE", 140, 22);

// Divider
doc.setDrawColor(220);
doc.line(20, 40, 190, 40);

// FROM
doc.setFontSize(13);
doc.setFont("helvetica", "bold");
doc.text("FROM", 20, 55);

doc.setFont("helvetica", "normal");
doc.setFontSize(11);

doc.text(company?.name || "", 20, 65);
doc.text(company?.email || "", 20, 72);
doc.text(company?.phone || "", 20, 79);

// BILL TO
doc.setFont("helvetica", "bold");
doc.setFontSize(13);
doc.text("BILL TO", 120, 55);

doc.setFont("helvetica", "normal");
doc.setFontSize(11);

doc.text(invoice.client_name || "", 120, 65);

if(invoice.email)
doc.text(invoice.email,120,72);

if(invoice.company)
doc.text(invoice.company,120,79);

// Divider
doc.line(20, 90, 190, 90);

// Invoice Details
doc.setFont("helvetica","bold");
doc.text("Project",20,105);

doc.setFont("helvetica","normal");
doc.text(invoice.project,20,113);

doc.setFont("helvetica","bold");
doc.text("Status",20,128);

doc.setFont("helvetica","normal");
doc.text(invoice.status,20,136);

// Total Box
doc.setFillColor(37,99,235);

doc.roundedRect(120,105,70,35,4,4,"F");

doc.setTextColor(255);

doc.setFont("helvetica","bold");

doc.setFontSize(12);
doc.text("TOTAL",145,118);

doc.setFontSize(20);
doc.text(`$${invoice.amount}`,137,132);

// Back to black
doc.setTextColor(0);

// Footer
doc.setDrawColor(220);

doc.line(20,270,190,270);

doc.setFontSize(10);

doc.text("Thank you for your business!",20,280);

doc.text("Generated by Freelancer SaaS",120,280);

// Save
doc.save(`invoice-${invoice.id}.pdf`);

};
const [invoice, setInvoice] = useState<any>(null);

useEffect(() => {

  async function loadInvoice() {

    const { data, error } = await supabase
      .from("invoices")
      .select("*")
      .eq("id", params.id)
      .single();

    if (error) {
      console.error(error);
      return;
    }

    setInvoice(data);

  }

  loadInvoice();

}, [params.id]);
 if(!invoice){
return <h1>Loading...</h1>
}

return (
<main className="min-h-screen bg-green-100 p-10">

<div className="max-w-3xl mx-auto bg-white rounded-3xl p-10 shadow-xl text-gray-900">
{company && company.logo && (
<img
src={company.logo}
alt="Company Logo"
className="w-32 h-32 object-contain mb-5 border-4 border-black rounded-xl bg-white"
/>
)}

<h1 className="text-4xl font-bold">
INVOICE
</h1>

<div className="mt-5">

<p className="font-bold">
Invoice #: {invoice.id}
</p>

<p>
Date: {new Date(invoice.date).toLocaleDateString()}
</p>

</div>


<hr className="my-6"/>


<h2 className="text-xl font-bold">
BILL TO
</h2>


<p className="mt-2">
Client: {invoice.client_name}
</p>

<p>
Email: {invoice.email}
</p>


<hr className="my-6"/>


<h2 className="text-xl font-bold">
PROJECT
</h2>


<p className="mt-2">
{invoice.project}
</p>


<div className="mt-8 bg-green-700 text-black  rounded-2xl p-6">


<p className="text-lg">
TOTAL
</p>


<p className="text-4xl font-bold">
${invoice.amount}
</p>


</div>


<div className="mt-5">

<p className="font-bold">
Status:
</p>


<p className="text-green-700 font-bold">
{invoice.status}
</p>


</div>


</div>
<button
className="mt-6 bg-black text-black font-bold px-6 py-3 rounded-xl hover:bg-gray-800 transition"
onClick={downloadPDF}
>
Download PDF
</button>
<button
 onClick={async () => {

  const response = await fetch("/api/send-email", {

    method: "POST",

    headers: {
      "Content-Type": "application/json",
    },

    body: JSON.stringify({
      to: invoice.email,
      subject: `Invoice ${invoice.id}`,
      html: `
        <h2>Hello ${invoice.client_name},</h2>

        <p>Please find your invoice.</p>

        <p><strong>Project:</strong> ${invoice.project}</p>

        <p><strong>Amount:</strong> $${invoice.amount}</p>

        <p>Thank you!</p>
      `,
    }),

  });

  if (response.ok) {
    alert("✅ Invoice email sent!");
  } else {
    alert("❌ Email failed.");
  }

}}
  className="mt-4 w-full bg-blue-600 hover:bg-blue-700 text-white py-3 rounded-xl font-semibold transition"
>
  📧 Email Invoice
</button>
</main>
);

}